image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
#  - test
  - deploy

#test:
#  stage: test
#  script:
#    - cd Adobe.Tests
#    - dotnet restore
#    - dotnet test
 
deploy:
  stage: deploy
  script:
    - cd Adobe
    - export VERSION=$(grep -oP '(?<=<Version>).*(?=</Version>)' Adobe.csproj)
    - dotnet build --configuration=Release
    - dotnet pack --configuration=Release
    - dotnet nuget push bin/Release/DentsuDataLab.Adobe.$VERSION.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
