image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
#  - test
  - deploy

#test:
#  stage: test
#  script:
#    - cd Adobe.Tests
#    - dotnet restore
#    - dotnet test
 
deploy:
  stage: deploy
  script:
    - cd Adobe
    - export VERSION=$(grep -oP '(?<=<Version>).*(?=</Version>)' Adobe.csproj)
    - echo $VERSION
    - dotnet build --configuration=Release
    - dotnet pack