// ReSharper disable InconsistentNaming
namespace Adobe.Models.General.Enums
{
    using System;

    [Serializable]
    public enum ErrorType
    {
        NO_FEATURE_ACCESS_TO_ADVANCED_CALCULATED_METRICS,
        INVALID_METRIC_ACCESS,
        METHOD_NOT_ALLOWED,
        RESOURCE_CONFLICT,
        INVALID_ACCESS,
        RESOURCE_TEMPORARILY_UNAVAILABLE,
        EXTERNAL_API_FAILURE,
        AAM_FAILURE,
        RESOURCE_ALREADY_EXISTS,
        INVALID_STATE,
        INVALID_JSON_INPUT,
        INVALID_PARAMETERS,
        INVALID_DIMENSION_ACCESS,
        UNSUPPORTED_DATA_TYPE,
        RESOURCE_NOT_FOUND,
        INSUFFICIENT_ACCESS,
        HEALTH_CHECK_ERROR,
        INVALID_DATA,
        UNEXPECTED_ERROR,
        EXTERNAL_API_ERROR,
        UNSUPPORTED_RESOURCE,
        IO_ERROR,
        INVALID_REQUEST,
        INVALID_CLIENT_ID,
        UNAUTHORIZED,
        AUTHORIZATION_ERROR,
        INVALID_TOKEN,
        INSUFFICIENT_SCOPE,
        BLUECOAT_UNAUTHORIZED
    }
}