name: .NET 2.2 CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test solution
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: Adobe.Tests
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Cache NuGet packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.nuget/packages # Mac/Linux
          key: ${{ hashFiles('*/packages.lock.json') }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 2.2.x

      - name: Run tests
        run: dotnet test --verbosity normal
