name: .NET 2.2 CD

on:
  release:
    types:
      - created

jobs:
  deploy:
    name: Push package
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: Adobe
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3.0.3
        with:
          path: ~/.nuget/packages # Mac/Linux
          key: ${{ hashFiles('*/packages.lock.json') }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 2.2.x

      - name: Get version number & set in env
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: echo "VERSION=$(echo "$TAG_NAME" | cut -c 2- )" >> $GITHUB_ENV

      - name: Pack project
        run: dotnet pack --configuration Release -p:PackageVersion=$VERSION

      - name: Push NuGet package
        run: dotnet nuget push bin/Release/DentsuDataLab.Adobe.$VERSION.nupkg -s "nuget.org" -k ${{ secrets.NUGET_AUTH_TOKEN }}
