name: .NET 2.2 CD
on:
  release:
    types:
      - created

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Adobe.Tests
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache NuGet packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.nuget/packages # Mac/Linux
          key: ${{ hashFiles('*/packages.lock.json') }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.x

      - name: Run tests
        run: dotnet test --verbosity normal

  deploy:
    name: Push package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Adobe
    timeout-minutes: 3
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache NuGet packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.nuget/packages # Mac/Linux
          key: ${{ hashFiles('*/packages.lock.json') }}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.x

      - name: Get version number & set as env
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: echo ::set-env name=VERSION::$( echo "$TAG_NAME" | cut -c 2- )

      - name: Pack project
        run: dotnet pack --configuration Release -p:PackageVersion=$VERSION

      - name: Push NuGet package
        run: dotnet nuget push bin/Release/DentsuDataLab.Adobe.$VERSION.nupkg -s "nuget.org" -k ${{ secrets.NUGET_AUTH_TOKEN }}
